### ISSUE TITLE
Regarding buttons for Admin Employee Data Management 

### ISSUE THREAD

**Issue by ank1tzzz** [Bijay-Gurung/HRMS#1]
![image](https://github.com/Bijay-Gurung/HRMS/assets/127822750/3699453d-f260-44ac-b340-b28420115a11)

Dear Bijay, do check out for some css properties and update it.

**Comment by Bijay-Gurung** [comment]
I have changed the button's positions and sizes.
![Two](https://github.com/Bijay-Gurung/HRMS/assets/127380445/326e1718-ce57-482a-baff-28399d52a498)
