### ISSUE TITLE
Improve the background

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#11]
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/2fabf6ab-ea47-46ac-9af4-b88a577c04bf)

**Comment by Bijay-Gurung** [comment]
![2](https://github.com/Bijay-Gurung/HRMS/assets/127380445/a51fa108-4d8d-44a7-9e43-e4fdc0b572d5)
