### ISSUE TITLE
Make side navigation bar functional

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#13]
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/eee92bad-3189-4b2f-8286-b54e5a4371b9)

**Comment by Bijay-Gurung** [comment]
![4](https://github.com/Bijay-Gurung/HRMS/assets/127380445/3a43431d-f560-418a-aadb-6aa09ab876dc)
