### ISSUE TITLE
Put actual content

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#14]
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/e4848f5d-5632-4300-a7da-0138d3033d1b)

**Comment by Bijay-Gurung** [comment]
![1](https://github.com/Bijay-Gurung/HRMS/assets/127380445/13a883e0-e35c-408a-8c84-9de2cf7caad1)
Done
