### ISSUE TITLE
 Employee image missing resolve it, also add validation

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#2]
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/f75a560a-5181-4f65-85fe-924596366934)
Resolve missing employee image on pageOne.php. Please add it for a complete profile display.

**Comment by Suraj-1000** [comment]
![Screenshot 2024-04-20 214241](https://github.com/Bijay-Gurung/HRMS/assets/127823021/cc023041-c509-49ee-883e-c320eb2cbe60)

The missing employee image on pageOne.php has been resolved. It's now included for a complete profile display.
