### ISSUE TITLE
Write proper description in Home page

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#3]
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/364a071e-7c07-4813-88c6-1f94a8040769)
Enhance the Home page experience on index.html with engaging content and intuitive navigation for a memorable user journey.

**Comment by Bijay-Gurung** [comment]
I had Implement the actual content.
![one](https://github.com/Bijay-Gurung/HRMS/assets/127380445/0d6da553-ef0f-415f-a1db-dc572546ff42)
