### ISSUE TITLE
Issue 1 releated to employee Attendance Checker 

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#4]
Solve the issue related to employee Attendance Checker 
![Screenshot 2024-05-16 161343](https://github.com/Bijay-Gurung/HRMS/assets/127823125/e3458612-97ed-412e-90ed-13e8253e222c)
![Screenshot 2024-05-16 161143](https://github.com/Bijay-Gurung/HRMS/assets/127823125/7d0da784-0d83-49dc-abe8-73c51ebd554c)

**Comment by Suraj-1000** [comment]
i have updated the css of it and added the navigatiin link and the problem has been resolved.
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823021/0451727f-dfbc-4dfc-990a-3b3c161aca95)
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823021/a6809310-cdf1-40b9-85a4-54aeb31ab426)
