### ISSUE TITLE
Issue 2 related to error alert message in login page

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#5]
Solve the issue it should display the error message while login
![Screenshot 2024-05-16 162125](https://github.com/Bijay-Gurung/HRMS/assets/127823125/81bc5533-990e-4e35-bea5-1cd1b0120b0e)

**Comment by Suraj-1000** [comment]
the issue regarding error message on email and password has been solved. if the user enter the wrong details it display the  error message, "Invalid Password" and "user doesnot exist" 
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823021/8d1e0f38-f5b4-4860-aa1e-91423c568592)
