### ISSUE TITLE
Issue 3 related to Populating the table

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#6]
include the php code to populated data in the table
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/8ee0871c-3875-4fa6-924b-a95262e9399a)

**Comment by Suraj-1000** [comment]
The issue related the populating table has been solved
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823021/156bec7b-347a-4302-a3b4-be4704062bda)
