### ISSUE TITLE
Issue 4 related to search functionality to search the data

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#7]
Modify the code to run the search functionality include the JS function in the code
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/0d9e6282-a80e-4bee-8ed9-5e0ff6bbecfe)

**Comment by Suraj-1000** [comment]
The issue regarding search functionality has been solved.
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823021/f2a470c8-da15-4eec-bf7f-fd181d263f7d)
