### ISSUE TITLE
Issue 5 related to include search field in the employee data management page

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#8]
Include the search field and button  in employee mode to search the employee data with their employee name. it doesnot have the code please include the search field and button code with their working functionality. i have attached the image where you need to align the field and the button
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/89200b05-2a0b-44d1-870f-44de3f0a40fb)

**Comment by Suraj-1000** [comment]
The issue related to include search field has been solved and it retrieve the data according to the employee name.
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823021/5467cc26-8a7f-4764-8760-7ef8cbbf48d5)
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823021/6f992c88-026d-4b5e-a039-4514d76d4f7b)
