### ISSUE TITLE
Fill the missing content

### ISSUE THREAD

**Issue by gaurab07chhetri** [Bijay-Gurung/HRMS#9]
![image](https://github.com/Bijay-Gurung/HRMS/assets/127823125/9a033467-be32-4931-a637-e53c370fc128)

**Comment by Bijay-Gurung** [comment]
![3](https://github.com/Bijay-Gurung/HRMS/assets/127380445/46d7edb5-9077-43a1-b7c9-b447e0c1a1e2)
![3 1](https://github.com/Bijay-Gurung/HRMS/assets/127380445/ad19fea5-54cb-4e74-9457-ec2c4ee5a365)
